/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package scientificcalculator;

/**
 *
 * @author verla
 */
public class ScientificCal extends javax.swing.JFrame {

    /**
     * Creates new form ScientificCal
     */
    public ScientificCal() {
        initComponents();
        jRadioButton1.setEnabled(false);
    }
    
    double num1, num2, result;
    String opr;
    
    public void enable(){
        jTextField1.setEnabled(true);
        
        jRadioButton1.setEnabled(false);
        jRadioButton2.setEnabled(true);
        
        jButton0.setEnabled(true);
        jButton1.setEnabled(true);
        jButton1divx.setEnabled(true);
        jButton2.setEnabled(true);
        jButton3.setEnabled(true);
        jButton4.setEnabled(true);
        jButton5.setEnabled(true);
        jButton6.setEnabled(true);
        jButton7.setEnabled(true);
        jButton8.setEnabled(true);
        jButton9.setEnabled(true);
        jButtonAdditionner.setEnabled(true);
        jButtonB.setEnabled(true);
        jButtonClr.setEnabled(true);
        jButtonCosh.setEnabled(true);
        jButtonCosinus.setEnabled(true);
        jButtonDiviser.setEnabled(true);
        jButtonEgal.setEnabled(true);
        jButtonExp.setEnabled(true);
        jButtonLog.setEnabled(true);
        jButtonMultiplier.setEnabled(true);
        jButtonNfactoriel.setEnabled(true);
        jButtonPlusOuMoins.setEnabled(true);
        jButtonPoint.setEnabled(true);
        jButtonPourcentage.setEnabled(true);
        jButtonR.setEnabled(true);
        jButtonSinh.setEnabled(true);
        jButtonSinus.setEnabled(true);
        jButtonSoustraire.setEnabled(true);
        jButtonTangeante.setEnabled(true);
        jButtonTanh.setEnabled(true);
        jButtonXepx2.setEnabled(true);
        jButtonXexp3.setEnabled(true);
        jButtonXexpY.setEnabled(true);
    }
    
    public void disable(){
        jTextField1.setEnabled(false);
        
        jRadioButton1.setEnabled(true);
        jRadioButton2.setEnabled(false);
        
        jButton0.setEnabled(false);
        jButton1.setEnabled(false);
        jButton1divx.setEnabled(false);
        jButton2.setEnabled(false);
        jButton3.setEnabled(false);
        jButton4.setEnabled(false);
        jButton5.setEnabled(false);
        jButton6.setEnabled(false);
        jButton7.setEnabled(false);
        jButton8.setEnabled(false);
        jButton9.setEnabled(false);
        jButtonAdditionner.setEnabled(false);
        jButtonB.setEnabled(false);
        jButtonClr.setEnabled(false);
        jButtonCosh.setEnabled(false);
        jButtonCosinus.setEnabled(false);
        jButtonDiviser.setEnabled(false);
        jButtonEgal.setEnabled(false);
        jButtonExp.setEnabled(false);
        jButtonLog.setEnabled(false);
        jButtonMultiplier.setEnabled(false);
        jButtonNfactoriel.setEnabled(false);
        jButtonPlusOuMoins.setEnabled(false);
        jButtonPoint.setEnabled(false);
        jButtonPourcentage.setEnabled(false);
        jButtonR.setEnabled(false);
        jButtonSinh.setEnabled(false);
        jButtonSinus.setEnabled(false);
        jButtonSoustraire.setEnabled(false);
        jButtonTangeante.setEnabled(false);
        jButtonTanh.setEnabled(false);
        jButtonXepx2.setEnabled(false);
        jButtonXexp3.setEnabled(false);
        jButtonXexpY.setEnabled(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jTextField1 = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jButtonR = new javax.swing.JButton();
        jButton1divx = new javax.swing.JButton();
        jButtonXexp3 = new javax.swing.JButton();
        jButtonXexpY = new javax.swing.JButton();
        jButtonXepx2 = new javax.swing.JButton();
        jButtonPlusOuMoins = new javax.swing.JButton();
        jButtonNfactoriel = new javax.swing.JButton();
        jButtonExp = new javax.swing.JButton();
        jButtonCosinus = new javax.swing.JButton();
        jButtonSinus = new javax.swing.JButton();
        jButtonTangeante = new javax.swing.JButton();
        jButtonTanh = new javax.swing.JButton();
        jButtonLog = new javax.swing.JButton();
        jButtonCosh = new javax.swing.JButton();
        jButtonSinh = new javax.swing.JButton();
        jButtonPourcentage = new javax.swing.JButton();
        jButtonClr = new javax.swing.JButton();
        jButtonAdditionner = new javax.swing.JButton();
        jButtonB = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButtonSoustraire = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButtonMultiplier = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButtonDiviser = new javax.swing.JButton();
        jButtonPoint = new javax.swing.JButton();
        jButtonEgal = new javax.swing.JButton();
        jButton0 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Scientific Calculator");
        setResizable(false);
        setType(java.awt.Window.Type.UTILITY);

        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jRadioButton1.setText("ON");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jRadioButton2.setText("OFF");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        jButtonR.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonR.setText("R");
        jButtonR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRActionPerformed(evt);
            }
        });

        jButton1divx.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1divx.setText("1/x");
        jButton1divx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1divxActionPerformed(evt);
            }
        });

        jButtonXexp3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonXexp3.setText("x^3");
        jButtonXexp3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonXexp3ActionPerformed(evt);
            }
        });

        jButtonXexpY.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonXexpY.setText("x^y");
        jButtonXexpY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonXexpYActionPerformed(evt);
            }
        });

        jButtonXepx2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonXepx2.setText("x^2");
        jButtonXepx2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonXepx2ActionPerformed(evt);
            }
        });

        jButtonPlusOuMoins.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonPlusOuMoins.setText("+/-");
        jButtonPlusOuMoins.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPlusOuMoinsActionPerformed(evt);
            }
        });

        jButtonNfactoriel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonNfactoriel.setText("n!");
        jButtonNfactoriel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNfactorielActionPerformed(evt);
            }
        });

        jButtonExp.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonExp.setText("exp");
        jButtonExp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExpActionPerformed(evt);
            }
        });

        jButtonCosinus.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonCosinus.setText("cos");
        jButtonCosinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCosinusActionPerformed(evt);
            }
        });

        jButtonSinus.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonSinus.setText("sin");
        jButtonSinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSinusActionPerformed(evt);
            }
        });

        jButtonTangeante.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonTangeante.setText("tan");
        jButtonTangeante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTangeanteActionPerformed(evt);
            }
        });

        jButtonTanh.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jButtonTanh.setText("tanh");
        jButtonTanh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTanhActionPerformed(evt);
            }
        });

        jButtonLog.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonLog.setText("log");
        jButtonLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLogActionPerformed(evt);
            }
        });

        jButtonCosh.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jButtonCosh.setText("cosh");
        jButtonCosh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCoshActionPerformed(evt);
            }
        });

        jButtonSinh.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonSinh.setText("sinh");
        jButtonSinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSinhActionPerformed(evt);
            }
        });

        jButtonPourcentage.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonPourcentage.setText("%");
        jButtonPourcentage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPourcentageActionPerformed(evt);
            }
        });

        jButtonClr.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonClr.setText("Clr");
        jButtonClr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClrActionPerformed(evt);
            }
        });

        jButtonAdditionner.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonAdditionner.setText("+");
        jButtonAdditionner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdditionnerActionPerformed(evt);
            }
        });

        jButtonB.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonB.setText("B");
        jButtonB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBActionPerformed(evt);
            }
        });

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton7.setText("7");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton9.setText("9");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton8.setText("8");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButtonSoustraire.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonSoustraire.setText("-");
        jButtonSoustraire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSoustraireActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton4.setText("4");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton6.setText("6");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton5.setText("5");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButtonMultiplier.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonMultiplier.setText("*");
        jButtonMultiplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMultiplierActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setText("2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton3.setText("3");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButtonDiviser.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonDiviser.setText("/");
        jButtonDiviser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDiviserActionPerformed(evt);
            }
        });

        jButtonPoint.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonPoint.setText(".");
        jButtonPoint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPointActionPerformed(evt);
            }
        });

        jButtonEgal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonEgal.setText("=");
        jButtonEgal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEgalActionPerformed(evt);
            }
        });

        jButton0.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton0.setText("0");
        jButton0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton0ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonR, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonExp, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonSinus, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonCosinus, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonTangeante, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1divx, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonLog, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonSinh, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonCosh, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonTanh, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonXexpY, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonPourcentage, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonClr, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonB, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonAdditionner, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonXexp3, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonSoustraire, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonXepx2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonMultiplier, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonNfactoriel, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonDiviser, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jRadioButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonPlusOuMoins, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton0, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonPoint, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonEgal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonR, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonExp, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonSinus, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonCosinus, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonTangeante, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1divx, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonLog, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonSinh, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonCosh, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonTanh, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonXexpY, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonPourcentage, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonClr, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAdditionner, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonB, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonXexp3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonSoustraire, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonXepx2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonMultiplier, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonNfactoriel, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonDiviser, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonPlusOuMoins, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton0, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonEgal, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonPoint, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton0ActionPerformed
        jTextField1.setText(jTextField1.getText() + "0");
    }//GEN-LAST:event_jButton0ActionPerformed

    private void jButtonPointActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPointActionPerformed
         jTextField1.setText(jTextField1.getText() + ".");
    }//GEN-LAST:event_jButtonPointActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         jTextField1.setText(jTextField1.getText() + "1");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         jTextField1.setText(jTextField1.getText() + "2");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
         jTextField1.setText(jTextField1.getText() + "3");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
         jTextField1.setText(jTextField1.getText() + "4");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
         jTextField1.setText(jTextField1.getText() + "5");
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        jTextField1.setText(jTextField1.getText() + "6");
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        jTextField1.setText(jTextField1.getText() + "7");
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
         jTextField1.setText(jTextField1.getText() + "8");
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
         jTextField1.setText(jTextField1.getText() + "9");
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButtonClrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClrActionPerformed
        jTextField1.setText(" ");
    }//GEN-LAST:event_jButtonClrActionPerformed

    private void jButtonBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBActionPerformed
        String backSpace = null;
        
        if(jTextField1.getText().length() > 0)
        {
            StringBuilder s = new StringBuilder(jTextField1.getText());
            
            s.deleteCharAt(jTextField1.getText().length() -1);
            backSpace = s.toString();
            jTextField1.setText(backSpace);
        }
    }//GEN-LAST:event_jButtonBActionPerformed

    private void jButtonAdditionnerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdditionnerActionPerformed
        num1 = Double.parseDouble(jTextField1.getText());
        
        jTextField1.setText(" ");
        
        opr = "+";
    }//GEN-LAST:event_jButtonAdditionnerActionPerformed

    private void jButtonSoustraireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSoustraireActionPerformed
          num1 = Double.parseDouble(jTextField1.getText());
        
        jTextField1.setText(" ");
        
        opr = "-";
    }//GEN-LAST:event_jButtonSoustraireActionPerformed

    private void jButtonMultiplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMultiplierActionPerformed
          num1 = Double.parseDouble(jTextField1.getText());
        
        jTextField1.setText(" ");
        
        opr = "*";
    }//GEN-LAST:event_jButtonMultiplierActionPerformed

    private void jButtonDiviserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDiviserActionPerformed
          num1 = Double.parseDouble(jTextField1.getText());
        
        jTextField1.setText(" ");
        
        opr = "/";
    }//GEN-LAST:event_jButtonDiviserActionPerformed

    private void jButtonPourcentageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPourcentageActionPerformed
         num1 = Double.parseDouble(jTextField1.getText());
        
        jTextField1.setText(" ");
        
        opr = "%";
    }//GEN-LAST:event_jButtonPourcentageActionPerformed

    private void jButtonEgalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEgalActionPerformed
        num2 = Double.parseDouble(jTextField1.getText());
        
        if(opr == "+")
        {
            result = num1 + num2;
            jTextField1.setText(Double.toString(result));
        }
        else if(opr == "-")
        {
            result = num1 - num2;
            jTextField1.setText(Double.toString(result));
        }
        else if (opr == "*")
        {
            result = num1 * num2;
            jTextField1.setText(Double.toString(result));
        }
        else if (opr == "/")
        {
            result = num1 / num2;
            jTextField1.setText(Double.toString(result));
        }
        else if (opr == "%")
        {
            result = num1 % num2;
            jTextField1.setText(Double.toString(result));
        }
        else if (opr == "x^y")
        {
            for (int i = 0; i < num2; i++) {
                result = num1 * num2;
            }
            jTextField1.setText(Double.toString(result));
        }
    }//GEN-LAST:event_jButtonEgalActionPerformed

    private void jButtonSinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSinusActionPerformed
        double t = Math.sin(Double.parseDouble(jTextField1.getText()));
        
        jTextField1.setText(" ");;
        jTextField1.setText(jTextField1.getText() + t);
    }//GEN-LAST:event_jButtonSinusActionPerformed

    private void jButtonCosinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCosinusActionPerformed
        double t = Math.cos(Double.parseDouble(jTextField1.getText()));
        
        jTextField1.setText(" ");;
        jTextField1.setText(jTextField1.getText() + t);
    }//GEN-LAST:event_jButtonCosinusActionPerformed

    private void jButtonTangeanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTangeanteActionPerformed
        double t = Math.tan(Double.parseDouble(jTextField1.getText()));
        
        jTextField1.setText(" ");;
        jTextField1.setText(jTextField1.getText() + t);
    }//GEN-LAST:event_jButtonTangeanteActionPerformed

    private void jButtonSinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSinhActionPerformed
        double t = Math.sinh(Double.parseDouble(jTextField1.getText()));
        
        jTextField1.setText(" ");;
        jTextField1.setText(jTextField1.getText() + t);
    }//GEN-LAST:event_jButtonSinhActionPerformed

    private void jButtonCoshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCoshActionPerformed
        double t = Math.cosh(Double.parseDouble(jTextField1.getText()));
        
        jTextField1.setText(" ");;
        jTextField1.setText(jTextField1.getText() + t);
    }//GEN-LAST:event_jButtonCoshActionPerformed

    private void jButtonTanhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTanhActionPerformed
        double t = Math.tanh(Double.parseDouble(jTextField1.getText()));
        
        jTextField1.setText(" ");;
        jTextField1.setText(jTextField1.getText() + t);
    }//GEN-LAST:event_jButtonTanhActionPerformed

    private void jButtonLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLogActionPerformed
        double t = Math.log(Double.parseDouble(jTextField1.getText()));
        
        jTextField1.setText(" ");;
        jTextField1.setText(jTextField1.getText() + t);
    }//GEN-LAST:event_jButtonLogActionPerformed

    private void jButtonExpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExpActionPerformed
        double t = Math.exp(Double.parseDouble(jTextField1.getText()));
        
        jTextField1.setText(" ");;
        jTextField1.setText(jTextField1.getText() + t);
    }//GEN-LAST:event_jButtonExpActionPerformed

    private void jButtonRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRActionPerformed
        double t = Math.sqrt(Double.parseDouble(jTextField1.getText()));
        
        jTextField1.setText(" ");;
        jTextField1.setText(jTextField1.getText() + t);
    }//GEN-LAST:event_jButtonRActionPerformed

    private void jButton1divxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1divxActionPerformed
        double t = 1/(Double.parseDouble(jTextField1.getText()));
        
        jTextField1.setText(" ");;
        jTextField1.setText(jTextField1.getText() + t);
    }//GEN-LAST:event_jButton1divxActionPerformed

    private void jButtonXepx2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonXepx2ActionPerformed
        double t = Double.parseDouble(jTextField1.getText());
        
        t = t * t;
        jTextField1.setText(" ");;
        jTextField1.setText(jTextField1.getText() + t);
    }//GEN-LAST:event_jButtonXepx2ActionPerformed

    private void jButtonXexp3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonXexp3ActionPerformed
        double t = Double.parseDouble(jTextField1.getText());
        
        t = t * t * t;
        jTextField1.setText(" ");;
        jTextField1.setText(jTextField1.getText() + t);
    }//GEN-LAST:event_jButtonXexp3ActionPerformed

    private void jButtonXexpYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonXexpYActionPerformed
        num1 = Double.parseDouble(jTextField1.getText());
        
        jTextField1.setText(" ");
        
        opr = "x^y";
    }//GEN-LAST:event_jButtonXexpYActionPerformed

    private void jButtonNfactorielActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNfactorielActionPerformed
        double t = Double.parseDouble(jTextField1.getText());
        
        double fact = 1;
        while(t!=0){
            fact = fact *t;
            t--;
        }
        jTextField1.setText(" ");;
        jTextField1.setText(jTextField1.getText() + fact);
    }//GEN-LAST:event_jButtonNfactorielActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        enable();
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        disable();
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jButtonPlusOuMoinsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPlusOuMoinsActionPerformed
        double t = Double.parseDouble(String.valueOf(jTextField1.getText()));
        
       t = t * (-1);
        jTextField1.setText(String.valueOf(t));
    }//GEN-LAST:event_jButtonPlusOuMoinsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ScientificCal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ScientificCal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ScientificCal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ScientificCal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ScientificCal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton0;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton1divx;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JButton jButtonAdditionner;
    private javax.swing.JButton jButtonB;
    private javax.swing.JButton jButtonClr;
    private javax.swing.JButton jButtonCosh;
    private javax.swing.JButton jButtonCosinus;
    private javax.swing.JButton jButtonDiviser;
    private javax.swing.JButton jButtonEgal;
    private javax.swing.JButton jButtonExp;
    private javax.swing.JButton jButtonLog;
    private javax.swing.JButton jButtonMultiplier;
    private javax.swing.JButton jButtonNfactoriel;
    private javax.swing.JButton jButtonPlusOuMoins;
    private javax.swing.JButton jButtonPoint;
    private javax.swing.JButton jButtonPourcentage;
    private javax.swing.JButton jButtonR;
    private javax.swing.JButton jButtonSinh;
    private javax.swing.JButton jButtonSinus;
    private javax.swing.JButton jButtonSoustraire;
    private javax.swing.JButton jButtonTangeante;
    private javax.swing.JButton jButtonTanh;
    private javax.swing.JButton jButtonXepx2;
    private javax.swing.JButton jButtonXexp3;
    private javax.swing.JButton jButtonXexpY;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
